### PR TITLE
Website Release - Content Translation [About Page] Indonesian

### PR DESCRIPTION
**Pull request by PardusEidolon**
Website builds no errors, feel free to do a review and approve @andrecahyadi give yourself a feel for the review process and merge the branch when finished.

_note:_ Just make sure you don't delete this branch ;-)

### CODE REVIEW

**Review by andrecahyadi — APPROVED** [review]
It's all clear

**Comment by andrecahyadi** [comment]
It really took me a while to make sure I didn't do anything stupid, only to merge this pull request from the main branch to the release branch, haha

**Comment by andrecahyadi** [comment]
What's next after being merged into the release branch?

**Comment by PardusEidolon** [comment]
Ka Pai!,

A github action kicks off and builds the site and the main site is rebuilt and deployed. theres nothing further for you to do here other than add more content or provide more translations. Your changes to the site should now be live :-)

**Comment by andrecahyadi** [comment]
Tena Koe! =)

Appreciate the explanation. I've checked the site and it's live now. 

Sure, I'll add more content or translations.

**Pull request merged**
