### PR TITLE
Dry Run github Action Update

### PR DESCRIPTION
**Pull request by PardusEidolon**
# Changelog - 21.05.2022

Changed the new `dry_run.yml` github action to include new time stamps, runs and markdown tables for a more clearer view of the outcome when changes to the website are made.

- Changed `dry_run.yml` to `jobSummary.yml`
- New Makdown table that includes:
    - Action run attempts for each step
    - Results of each of the steps
    - Step ID's
- Added a time and date stamp.

### CODE REVIEW

**Comment by andrecahyadi** [comment]
Hi Jack @PardusEidolon So, are you going to change this file?
image

In which part exactly the changes will be shown?
image

**Comment by andrecahyadi** [comment]
@PardusEidolon 
As a reviewer, if everything is fine, what should I do next? Merge pull request? And close with comment?

**Comment by PardusEidolon** [comment]
> @PardusEidolon As a reviewer, if everything is fine, what should I do next? Merge pull request? And close with comment?

apologies for the late reply been busy! everything you just said but it's really up to you if you want to go ahead and merge thats fine typically all I need is just the approval and I would go ahead and manage my own branch

**Comment by andrecahyadi** [comment]
> > @PardusEidolon As a reviewer, if everything is fine, what should I do next? Merge pull request? And close with comment?
> 
> apologies for the late reply been busy! everything you just said but it's really up to you if you want to go ahead and merge thats fine typically all I need is just the approval and I would go ahead and manage my own branch

@PardusEidolon No probs, man, haha. Ok, noted.

**Pull request merged**
