### PR TITLE
Content Enhancement Indonesian - 15-05-2022

### PR DESCRIPTION
**Pull request by andrecahyadi**
Added:

- content/id/docs/Cardano360/Apr-22.md
- content/id/docs/Cardano360/Feb-22.md
- content/id/docs/Cardano360/Jan-22.md
- content/id/docs/Cardano360/Mar-22.md
- content/id/docs/Cardano360/_index.md
- content/id/docs/Seputar Cardano/ouroboros-di-pos-cardano.md
- content/id/docs/Seputar Cardano/stake-pool-di-cardano.md
- content/id/docs/Seputar Cardano/stake-pool-vs-sybil-attack.md

Minor Revision:
- content/id/docs/Seputar Cardano/serba-serbi-staking-ada.md

### CODE REVIEW

**Review by PardusEidolon — CHANGES_REQUESTED** [review]
@andrecahyadi you'll have to also put in a `_index.md` inside the other directory for it to be visible in the nav bar with your nested markdown file pages

**Comment by PardusEidolon** [comment]
An exercise @andrecahyadi;

See if you can get it to build locally on your machine with hugo before pushing into this remote branch so that your happy with the results before a merge is submitted.

**Comment by andrecahyadi** [comment]
> @andrecahyadi you'll have to also put in a `_index.md` inside the other directory `Seputar Cardano` for it to be visible in the nav bar with your nested markdown file pages

Hi Jack @PardusEidolon, the '_index.md' file has been there =)
image

**Comment by PardusEidolon** [comment]
> > @andrecahyadi you'll have to also put in a `_index.md` inside the other directory `Seputar Cardano` for it to be visible in the nav bar with your nested markdown file pages
> 
> Hi Jack @PardusEidolon, the '_index.md' file was already created before =) image

Right you are! apologies I was looking at the files changed not the ones that exist in the repository

**Review by PardusEidolon — APPROVED** [review]

**Comment by PardusEidolon** [comment]
Merging into main branch now

**Pull request merged**
