### PR TITLE
Content [Catalyst TV]: Add new episodes to CatalystTV 

### PR DESCRIPTION
**Pull request by PardusEidolon**
More than 10 episodes have been uploaded but not added to the main website, new pages need to be created as well as a template for easy integration with the website.

I will upload the remaining episodes in english as a base for translation and to get things started.

### CODE REVIEW

**Comment by PardusEidolon** [comment]
@Mietran0407 here is the PR where ive uploaded all your videos too on the website

**Comment by andrecahyadi** [comment]
Hi, Jack @PardusEidolon.
During the review, I made some changes, marked it as Resolved, and then confirmed Merge.
Is that correct?

**Comment by PardusEidolon** [comment]
@andrecahyadi you did good! good job fixing the merge conflict 👍

I'm merging and closing this PR now

**Comment by andrecahyadi** [comment]
@PardusEidolon Thanks, Jack :)
Anyway during the review, if I found any typos, I click the Viewed check box and then just write a comment? 
Does the creator then need to revise & re-commit?

**Pull request merged**
